config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("graph_recsys.urls", namespace="recsys")),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import RegisterView, ProfileView, NewPasswordView, email_verification
from users.apps import UsersConfig

app_name = UsersConfig.name

# урлы приложения users
urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("reset-pasword/", NewPasswordView.as_view(), name="reset-password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    """
    Модель пользователя
    """

    username = None
    first_name = models.CharField(max_length=100, verbose_name="имя")
    email = models.EmailField(unique=True, verbose_name="почта")
    avatar = models.ImageField(
        upload_to="users/avatars", verbose_name="аватар", **NULLABLE
    )
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.first_name

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordResetForm,
)
from django import forms
from django.forms import BooleanField

from users.models import User


class StyleFormMixin:
    """
    класс-миксин для стилизации форм
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class UserRegistrationForm(StyleFormMixin, UserCreationForm):
    """
    Форма регистрации пользователя
    """

    class Meta:
        model = User
        fields = ("first_name", "email", "password1", "password2")


class UserProfileForm(StyleFormMixin, UserChangeForm):
    """
    Форма профиля пользователя
    """

    class Meta:
        model = User
        fields = (
            "first_name",
            "email",
            "avatar",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()


class PasswordForm(StyleFormMixin, PasswordResetForm):
    """
    Форма сброса пароля
    """

    class Meta:
        model = User
        fields = ("email",)

users/views.py
import secrets, string, random
from django.core.mail import send_mail
from django.db.models.base import Model as Model
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy, reverse
from users.models import User
from graph_recsys.models import Prefer
from users.forms import UserRegistrationForm, UserProfileForm, PasswordForm


class RegisterView(CreateView):
    """
    контроллер регистрации пользователя
    """

    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        Prefer.objects.create(user=user)
        user.is_active = True

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class ProfileView(UpdateView):
    """
    контроллер редактирования профиля пользователя
    """

    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class NewPasswordView(PasswordResetView):
    """
    контроллер сброса пароля пользователя
    """

    model = User
    form_class = PasswordForm
    template_name = "users/reset_password.html"
    success_url = reverse_lazy("users/login.html")

    def generate_password(self, length):
        characters = string.ascii_letters + string.digits + string.punctuation
        password = "".join(random.choice(characters) for _ in range(length))
        return password

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        user = get_object_or_404(User, email=email)
        password = self.generate_password(16)
        user.set_password(password)
        user.save()
        send_mail(
            subject="вы запросили сброс пароля",
            message=f"новый пароль для входа: {password}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return redirect(reverse("users:login"))

users/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailings</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <header data-bs-theme="dark">
        <div class="collapse text-bg-dark" id="navbarHeader">
          <div class="container d-flex justify-content-end">
            <div class="row">
              <div class="col-sm-4 offset-md-1 py-4">
                <h4>menu</h4>
                <ul class="list-unstyled">
                    <li>
                    {% if user.is_authenticated %}
                        <form action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-link link-light link-underline link-underline-opacity-0" type="submit">выйти</button>
                        </form>

                        <a class="link-light nav-link-active link-underline link-underline-opacity-0" href="{% url 'users:profile' %}">профиль</a>
                        <a class="link-light nav-link-active link-underline link-underline-opacity-0" href="{% url 'graph_recsys:main' %}">главная</a>
                        <a class="link-light nav-link-active link-underline link-underline-opacity-0" href="{% url 'graph_recsys:statistics' %}">статистика</a>
                    {% else %}
                        <a class="link-light nav-link-active link-underline link-underline-opacity-0" href="{% url 'users:login' %}">войти</a>
                        <a class="link-light nav-link-active link-underline link-underline-opacity-0" href="{% url 'users:register' %}">регистрация</a>
                    {% endif %}
                    </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container">
            <div class='navbar'>
                <strong>mailings</strong>
              </a>
                <strong>blog</strong>
              </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </header>

{% block content %}
{% endblock %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
<footer class="text-body-secondary py-5">
  </footer>
</html>